### PR TITLE
Add installation to README

### PR DESCRIPTION
**Pull request by egourlao**
This is a small PR that solves #2. It adds spacing in the README, some anchors, as well as an *Installation* section.

### CODE REVIEW

**Comment by anestv** [comment]
~~This only downloades this source code, it doesn't compile it.~~

~~If you add another line, `go build github.com/goggle/flatten`, wouldn't that be better?~~

**Comment by egourlao** [comment]
Hmm, it actually does, though!

```
$ go help get
usage: go get [-d] [-f] [-fix] [-insecure] [-t] [-u] [build flags] [packages]

Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.

[...]
```

It can easily be tested with a Docker container:

```
$ docker run -it golang:latest
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
Digest: sha256:0bc4b605f127ebcda9c96d8b0411780e8dcc03ee695c5f9cdf6298f9977b8ca8
Status: Downloaded newer image for golang:latest
root@95db6b6811fc:/go# go get github.com/goggle/flatten
root@95db6b6811fc:/go# which flatten
/go/bin/flatten
root@95db6b6811fc:/go# flatten
Flatten performs changes on the file system. Do you want to simulate this process first? [y]/n: n

**Review by goggle — APPROVED** [review]
Looks good, thank you.

**Comment by anestv** [comment]
@dotpy3 you were right.
In my installation it wasn't working, probably because $GOPATH/bin was not included in my $PATH

**Pull request merged**
